---
openapi: "3.0.0"
info: 
  title: "Api3"
  version: "1.0.0"
servers: 
- url: "localhost:3000"
  description: "Api3 server"
paths: 
  /auth/login: 
    post: 
      summary: ""
      parameters: 
      requestBody: 
        content: 
          application/json: 
            schema: 
              type: "object"
              properties: 
                email_user: 
                  type: "string"
                pass_user: 
                  type: "string"
        required: "false"
      responses: 
        200: 
          description: ""
          content: 
            application/json: 
              schema: 
                type: "object"
                properties: 
                  type_user: 
                    type: "number"
        401: 
          description: ""
          content: 
            application/json: 
              schema: 
                type: "object"
                properties: 
                  message: 
                    type: "string"
  /auth/signUp: 
    post: 
      summary: ""
      parameters: 
      requestBody: 
        content: 
          application/json: 
            schema: 
              type: "object"
              properties: 
                name_user: 
                  type: "string"
                surname_user: 
                  type: "string"
                age_user: 
                  type: "string"
                email_user: 
                  type: "string"
                pass_user: 
                  type: "string"
                type_user: 
                  type: "number"
                ban_until_date: 
                  type: "object"
                  properties: 
        required: "false"
      responses: 
        200: 
          description: ""
          content: 
            application/json: 
              schema: 
                type: "object"
                properties: 
                  message: 
                    type: "string"
  /verificaUserType/is_logged: 
    get: 
      summary: ""
      parameters: 
      responses: 
        200: 
          description: ""
          content: 
            application/json: 
              schema: 
                type: "object"
                properties: 
                  _id: 
                    type: "string"
                  name_user: 
                    type: "string"
                  surname_user: 
                    type: "string"
                  age_user: 
                    type: "number"
                  email_user: 
                    type: "string"
                  pass_user: 
                    type: "string"
                  type_user: 
                    type: "number"
                  ban_until_date: 
                    type: "object"
                    properties: 
                  __v: 
                    type: "number"
  /bookings/get/{id}: 
    get: 
      summary: ""
      parameters: 
      - name: "id"
        in: "path"
        required: "true"
        schema: 
          type: "string"
      responses: 
        200: 
          description: ""
          content: 
            application/json: 
              schema: 
                type: "array"
                items: 
                  type: "undefined"
  /tags/get: 
    get: 
      summary: ""
      parameters: 
      responses: 
        200: 
          description: ""
          content: 
            application/json: 
              schema: 
                type: "array"
                items: 
                  type: "undefined"
  /suggEvents/get: 
    get: 
      summary: ""
      parameters: 
      responses: 
        200: 
          description: ""
          content: 
            application/json: 
              schema: 
                type: "array"
                items: 
                  type: "undefined"
  /events/not_expired: 
    get: 
      summary: ""
      parameters: 
      responses: 
        404: 
          description: ""
          content: 
            application/json: 
              schema: 
                type: "object"
                properties: 
                  message: 
                    type: "string"
  /verificaUserType/is_data_analyst: 
    get: 
      summary: ""
      parameters: 
      responses: 
        200: 
          description: ""
          content: 
            application/json: 
              schema: 
                type: "object"
                properties: 
                  _id: 
                    type: "string"
                  name_user: 
                    type: "string"
                  surname_user: 
                    type: "string"
                  age_user: 
                    type: "number"
                  email_user: 
                    type: "string"
                  pass_user: 
                    type: "string"
                  type_user: 
                    type: "number"
                  ban_until_date: 
                    type: "object"
                    properties: 
                  __v: 
                    type: "number"
  /bookings/get: 
    get: 
      summary: ""
      parameters: 
      responses: 
        200: 
          description: ""
          content: 
            application/json: 
              schema: 
                type: "array"
                items: 
                  type: "undefined"
  /events/get: 
    get: 
      summary: ""
      parameters: 
      responses: 
        200: 
          description: ""
          content: 
            application/json: 
              schema: 
                type: "array"
                items: 
                  type: "undefined"
  /users/public_for_mod: 
    get: 
      summary: ""
      parameters: 
      responses: 
        200: 
          description: ""
          content: 
            application/json: 
              schema: 
                type: "array"
                items: 
                  type: "object"
                  properties: 
                    _id: 
                      type: "string"
                    name_user: 
                      type: "string"
                    surname_user: 
                      type: "string"
                    age_user: 
                      type: "number"
                    email_user: 
                      type: "string"
                    ban_until_date: 
                      type: "object"
                      properties: 
  /verificaUserType/is_mod: 
    get: 
      summary: ""
      parameters: 
      responses: 
        200: 
          description: ""
          content: 
            application/json: 
              schema: 
                type: "object"
                properties: 
                  _id: 
                    type: "string"
                  name_user: 
                    type: "string"
                  surname_user: 
                    type: "string"
                  age_user: 
                    type: "number"
                  email_user: 
                    type: "string"
                  pass_user: 
                    type: "string"
                  type_user: 
                    type: "number"
                  ban_until_date: 
                    type: "object"
                    properties: 
                  __v: 
                    type: "number"
  /users/suspend: 
    patch: 
      summary: ""
      parameters: 
      requestBody: 
        content: 
          application/json: 
            schema: 
              type: "object"
              properties: 
                ban_until_date: 
                  type: "string"
                user_id: 
                  type: "string"
        required: "false"
      responses: 
        200: 
          description: ""
          content: 
            application/json: 
              schema: 
                type: "object"
                properties: 
                  message: 
                    type: "string"
                  user: 
                    type: "object"
                    properties: 
                      _id: 
                        type: "string"
                      name_user: 
                        type: "string"
                      surname_user: 
                        type: "string"
                      age_user: 
                        type: "number"
                      email_user: 
                        type: "string"
                      pass_user: 
                        type: "string"
                      type_user: 
                        type: "number"
                      ban_until_date: 
                        type: "string"
                      __v: 
                        type: "number"
  /users/unsuspend: 
    patch: 
      summary: ""
      parameters: 
      requestBody: 
        content: 
          application/json: 
            schema: 
              type: "object"
              properties: 
                user_id: 
                  type: "string"
        required: "false"
      responses: 
        200: 
          description: ""
          content: 
            application/json: 
              schema: 
                type: "object"
                properties: 
                  message: 
                    type: "string"
                  user: 
                    type: "object"
                    properties: 
                      _id: 
                        type: "string"
                      name_user: 
                        type: "string"
                      surname_user: 
                        type: "string"
                      age_user: 
                        type: "number"
                      email_user: 
                        type: "string"
                      pass_user: 
                        type: "string"
                      type_user: 
                        type: "number"
                      ban_until_date: 
                        type: "object"
                        properties: 
                      __v: 
                        type: "number"